name: React Build

on:
  push:
    branches: [ "main", "gh-pages" ]
  pull_request:
    branches: [ "main", "gh-pages" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd website && npm run build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        # Artifact name
        name: github-pages
        # Path of the directory containing the static assets.
        path: website/build
        # Duration after which artifact will expire in days.
        retention-days: 1
          
