name: React Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd website/
        cd website && npm install && npm run build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        # Path of the directory containing the static assets.
        path: website/build
        
  deploy:
   needs: build
   permissions:
    id-token: write
    pages: write
   if: ${{ github.ref_name == 'main' }}
   runs-on: ubuntu-latest
   steps:
   - name: Deploy GitHub Pages site
     uses: actions/deploy-pages@v4.0.4
          
